### PR TITLE
Kaiju database updates

### PR DESCRIPTION
**Pull request by jungbluth**
Updates to all four databases - now using latest versions from early 2011. 

Passing local tests on docker03.

 @dcchivian is probably best to review, but @bio-boris could also manage given the brevity. Once accepted I can register and test in appdev.

### CODE REVIEW

**Comment by dcchivian** [comment]
1. Since update is not minor (Kaiju version is changing, dbs are changing), the module version should be changed to 1.2.0.
2. The App title in the display.yaml should be to v1.8.0, not v1.7.4.
3. The dates of the db releases should be in the description text in the display.yaml.
4. In future, you should do the merge from a kbaseapps branch not a person fork, so the Github Actions tests can access the KBase secrets token.  They will fail otherwise.  This time is ok, but next time make a branch in kbaseapps first (such as "develop").  You can merge to that branch from your fork if you need to, and then merge to master.

**Comment by jungbluth** [comment]
Not ready for merging yet because I've yet to test the new databases. I'll post a message when ready.

1. Version bumped to 1.2.0
2.  Kaiju binaries installed using existing docker image still point to v1.7.4 - not sure why the Kaiju documentation says v1.8. v1.7.4 is correct as of today.
3. Database dates added
4. Got it, thanks for this info. Will follow this route next time around.

**Comment by jungbluth** [comment]
Okay, ready for your review, @dcchivian - this is passing all local tests using kb-sdk test. The new fungi|virus|rvdb|plasmid database additions were easy. I'll test each one inside a narrative, once able.

**Comment by dcchivian** [comment]
@jungbluth looks good!  merging PR

**Pull request merged**
